import { BaseEntity } from './../../shared';
import { AccountsReceivable } from '../accounts-receivable/accounts-receivable.model';

export const enum BudderflyInvoiceStatus {
    IN_PROGRESS = 'IN_PROGRESS',
    PENDING_APPROVAL = 'PENDING_APPROVAL',
    APPROVED = 'APPROVED',
    SENT = 'SENT',
    REJECTED = 'REJECTED',
    LOCKED = 'LOCKED',
    ON_HOLD = 'ON_HOLD',
    WAITING = 'WAITING',
    FAILED = 'FAILED',
    VALIDATION_PASS = 'VALIDATION_PASS',
    VALIDATION_FAILED = 'VALIDATION_FAILED'
}

export const enum BillingRequestStatus {
    'New',
    'AMEResearch',
    'AMEApproved',
    'AMEGenerated',
    'AMEPendingApproval',
    'UrjanetHistoryReceived',
    'UrjanetHistoryRequested',
    'UrjanetNotEnoughHistory',
    'CredentialsBlocked'
}

export class BudderflyInvoice implements BaseEntity {
    constructor(
        public id?: number,
        public budderflyId?: string,
        public invoiceNumber?: string,
        public lastInvoice?: any,
        public contactName?: string,
        public contactEmail?: string,
        public LEDInstallDate?: any,
        public accountTakeOverDate?: any,
        public utilityProvider?: string,
        public tariff?: string,
        public address?: string,
        public city?: string,
        public state?: string,
        public zipCode?: string,
        public message?: string,
        public country?: string,
        public arrears?: boolean,
        public discount?: number,
        public priorBalance?: number,
        public paymentsCredits?: number,
        public totalNewElectricCharges?: number,
        public totalOtherCharges?: number,
        public taxes?: number,
        public totalNewCharges?: number,
        public amountDue?: number,
        public pdfUrl?: string,
        public approvedBy?: string,
        public approvedDate?: any,
        public rejectedBy?: string,
        public rejectedDate?: any,
        public rejectionNotes?: string,
        public budderflyInvoiceStatus?: BudderflyInvoiceStatus,
        public billingCycleId?: number,
        public previousPdfUrl?: string,
        public previousInvoiceNumber?: number,
        public siteId?: number,
        public discountAmount?: number,
        public fullAmount?: number,
        public startDate?: any,
        public endDate?: any,
        public statementDate?: any,
        public dueDate?: any,
        public billingDays?: number,
        public createdBy?: string,
        public lastModifiedBy?: string,
        public lastModifiedDate?: any,
        public createdDate?: any,
        public accountsReceivableId?: number,
        public billingAddress?: string,
        public billingCity?: string,
        public billingState?: string,
        public billingZipCode?: string,
        public billingCountry?: string,
        public utilityAccountNumber?: string,
        public generatedDate?: any,
        public chargesGeneratedDate?: any,
        public solutionsGeneratedDate?: any,
        public accountsReceivablesGeneratedDate?: any,
        public performancesGeneratedDate?: any,
        public yearToDateSavings?: number,
        public programToDateSavings?: number,
        public discountedUsage?: number,
        public supplyChargeReduction?: number,
        public reducedTaxes?: number
    ) {
        this.arrears = false;
    }
}
